module.exports={
    signInController:require('./signInController'),
    signUpController:require('./signUpController'),
    searchController:require('./searchController'),
    friendsController:require('./friendsController'),
    profileController:require('./profileController'),
    timelineController:require('./timelineController'),
    authController:require('./auth')
}